from sqlalchemy import Column, String, Text, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from .base import BaseModel, UUIDType


class GeneratedFile(BaseModel):
    """A file generated by the code generation pipeline."""
    __tablename__ = "generated_files"

    project_id = Column(UUIDType, ForeignKey("generation_projects.id"), nullable=False)
    file_path = Column(String(1024), nullable=False)
    content = Column(Text, nullable=False)
    language = Column(String(50), nullable=True)
    step = Column(String(50), nullable=False)
    is_binary = Column(Boolean, default=False)
    checksum = Column(String(64), nullable=True)
    status = Column(String(20), default="pending")

    # Relationships
    project = relationship("GenerationProject", back_populates="files")

    def __repr__(self):
        return f"<GeneratedFile {self.file_path}>"
